INSERT INTO `jajo-navi`.`address` (`name`, `hierarchy`) VALUES ('Dom', 1)
INSERT INTO `jajo-navi`.`address` (`name`, `hierarchy`) VALUES ('Sebastian', 2)
INSERT INTO `jajo-navi`.`address` (`name`, `hierarchy`) VALUES ('Niepołomicka 10/3213', 3)
INSERT INTO `jajo-navi`.`address` (`name`, `hierarchy`) VALUES ('Nie wiem jeszcze co', 4)
INSERT INTO `jajo-navi`.`address` (`name`, `hierarchy`) VALUES ('Gabi', 5)
INSERT INTO `jajo-navi`.`product` (`name`, `price`, `cost`, `hierarchy`) VALUES ('Jajka', 25, 18, 1)
INSERT INTO `jajo-navi`.`product` (`name`, `price`, `cost`, `hierarchy`) VALUES ('Miód rzepakowy duży', 38, 31, 2)
INSERT INTO `jajo-navi`.`product` (`name`, `price`, `cost`, `hierarchy`) VALUES ('Miód rzepakowy średni', 25, 20, 3)
INSERT INTO `jajo-navi`.`product` (`name`, `price`, `cost`, `hierarchy`) VALUES ('Miód rzepakowy mały', 15, 10, 4)
INSERT INTO `jajo-navi`.`emporium` (`name`) VALUES ('Test Emporium')
INSERT INTO `jajo-navi`.`emporium` (`name`) VALUES ('Test Emporium 2')
INSERT INTO `jajo-navi`.`transport` (`time`, `address_id`, `message_id`, `emporium_id`) VALUES (100000, 1, 1, 1)
INSERT INTO `jajo-navi`.`transport` (`time`, `address_id`, `message_id`, `emporium_id`) VALUES (150000, 2, 1, 1)
INSERT INTO `jajo-navi`.`transport` (`time`, `address_id`, `message_id`, `emporium_id`) VALUES (160000, 3, 1, 1)
INSERT INTO `jajo-navi`.`transport` (`time`, `address_id`, `message_id`, `emporium_id`) VALUES (170000, 4, 1, 1)
INSERT INTO `jajo-navi`.`transport` (`time`, `address_id`, `message_id`, `emporium_id`) VALUES (160000, 1, 1, 2)
INSERT INTO `jajo-navi`.`transport` (`time`, `address_id`, `message_id`, `emporium_id`) VALUES (170000, 5, 1, 2)
INSERT INTO `jajo-navi`.`message` (`name`, `message`) VALUES ('default', 'Hej. Będę w niedzielę u Ciebie o ')
INSERT INTO `jajo-navi`.`count` (`count`, `product_id`, `transport_id`) VALUES (2, 1, 5)
INSERT INTO `jajo-navi`.`count` (`count`, `product_id`, `transport_id`) VALUES (1, 2, 5)
INSERT INTO `jajo-navi`.`count` (`count`, `product_id`, `transport_id`) VALUES (6, 1, 6)

